function code = getCodeHistoryStruct()

code = struct('create', ['p = load(''params.mat'');\n' ...
                         'vp = load(''vParams.mat'');\n'...
                         'Params = p.params;\n'...
                         'VisualisationParams = vp.vParams;\n\n'...
                         'project = Project(''%s'', ''%s'', ''newResultsFolder_%s_results'', ''%s'', Params, VisualisationParams);\n'...
                         'project.preprocessAll();\n'], ...
              'interpolate', 'project.interpolateSelected();\n'...
              );
                

end